### ISSUE TITLE
Share common files with examples

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx-rs#32]
## Brief feature description

The examples duplicate the struct with the data transmitted via shared memory. This is error prone when the struct is changed in one example but not in another one. The struct should be shared with all examples.

Check if this can be done by a static lib like
```toml
[[example]]
name = "shm-data"
crate-type = ["staticlib"]
```
